apiVersion: apps/v1
kind: Deployment
metadata:
  name: Driver
  labels:
    app: Driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Driver
  template:
    metadata:
      labels:
        app: Driver
    spec:
      containers:
        - name: Driver
          image: username/Driver:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5